FROM microsoft/aspnetcore-build:2.0.0-nanoserver as build
COPY . .
WORKDIR C:/WebAPI/
RUN dotnet restore
RUN dotnet publish -o C:/app --configuration Debug

FROM microsoft/aspnetcore:2.0.0-nanoserver
ENV Redis_Hostname=redis Redis_Port=6379
EXPOSE 80
COPY --from=build c:/app .
ENTRYPOINT ["dotnet","WebAPI.dll"]