version: '3.3'
networks:
  default:
    external:
      name: nat
volumes:
  redis_data:
    external: true
services:
  redis:
    image: redis:nanoserver
    ports:
     - 6379:6379
    hostname: redis
    restart: always
    volumes:
     - redis_data:c:/data
  webapi:
    image: operationsdashboard/webapi
    ports:
     - 80:80
    links:
     - redis
    hostname: webapi
    restart: always
  pinger:
    image: operationsdashboard/pinger
    links:
     - redis
  dashboard:
    image: operationsdashboard/dashboard
    ports:
     - 5000:80
    links:
     - webapi