version: '3.3'
networks:
  default:
    external:
      name: nat
volumes:
  redis:
services:
  redis:
    image: redis:nanoserver
    ports:
     - 6379:6379
    hostname: redis
    restart: always
    volumes:
     - redis:c:/data
  webapi:
    image: operationsdashboard/webapi
    ports:
     - 80:80
    links:
     - redis
    hostname: webapi
    restart: always
  dataseed:
    image: operationsdashboard/dataseed
    links:
     - webapi
    restart: on-failure
    environment:
     - Servermapping_Limit=10